"""
PyTorch Dataset and DataLoader utilities for SpecMAE.

Dataset layout expected on disk (generated by mix_desert_data.py):

    data/desert/
    ├── train/normal/       normal clips for training
    ├── val/normal/         normal clips for validation
    └── test/
        ├── normal/         normal clips for testing
        └── anomaly/
            ├── snr_-10dB/
            ├── snr_+0dB/
            └── ...

Label convention:
    0 = normal   (no anomaly)
    1 = anomaly
"""
from __future__ import annotations

from pathlib import Path
from typing import Callable, Optional

import torch
from torch.utils.data import DataLoader, Dataset, Subset

from .feature_extraction import AudioConfig, LogMelExtractor


def _auto_pin_memory() -> bool:
    """pin_memory only benefits CUDA (page-locked host → GPU DMA)."""
    return torch.cuda.is_available()


# ═══════════════════════════════════════════════════════════════════════════
#  Dataset
# ═══════════════════════════════════════════════════════════════════════════

class AudioDataset(Dataset):
    """
    Flat WAV file dataset with optional label.

    Every sample is a log-Mel spectrogram tensor of shape (1, n_mels, T).

    Args:
        root:        Directory containing WAV files (recursive search).
        extractor:   LogMelExtractor instance.
        label:       Integer label applied to every sample in this dataset.
                     0 = normal, 1 = anomaly.
        transform:   Optional callable applied to the spectrogram tensor.
        extensions:  Supported audio file extensions.
    """

    def __init__(
        self,
        root:       str | Path,
        extractor:  LogMelExtractor,
        label:      int = 0,
        transform:  Optional[Callable] = None,
        extensions: tuple[str, ...] = (".wav", ".flac", ".mp3"),
    ) -> None:
        self.extractor = extractor
        self.label     = label
        self.transform = transform

        root = Path(root)
        self.files = sorted(
            p for ext in extensions for p in root.rglob(f"*{ext}")
        )
        if not self.files:
            raise FileNotFoundError(f"No audio files found under {root}")

    def __len__(self) -> int:
        return len(self.files)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, int]:
        spec = self.extractor(str(self.files[idx]))   # (1, n_mels, T)
        if self.transform is not None:
            spec = self.transform(spec)
        return spec, self.label


# ═══════════════════════════════════════════════════════════════════════════
#  Concatenated anomaly test set
# ═══════════════════════════════════════════════════════════════════════════

class AnomalyTestDataset(Dataset):
    """
    Combined test dataset: normal clips (label=0) + anomaly clips per SNR
    (label=1), with per-sample SNR metadata.

    Args:
        normal_dir:  Directory with normal test clips.
        anomaly_dir: Parent directory whose immediate subdirectories are
                     named snr_-10dB, snr_+0dB, … Each sub-folder holds
                     anomaly clips for that SNR.
        extractor:   LogMelExtractor.
        snr_values:  SNR levels to include (default: all sub-dirs).
    """

    def __init__(
        self,
        normal_dir:  str | Path,
        anomaly_dir: str | Path,
        extractor:   LogMelExtractor,
        snr_values:  Optional[list[int]] = None,
    ) -> None:
        self.extractor = extractor
        self.samples: list[tuple[Path, int, str]] = []   # (path, label, snr_tag)

        # Normal samples
        for p in sorted(Path(normal_dir).glob("*.wav")):
            self.samples.append((p, 0, "normal"))

        # Anomaly samples, one sub-folder per SNR
        anomaly_root = Path(anomaly_dir)
        for snr_dir in sorted(anomaly_root.iterdir()):
            if not snr_dir.is_dir():
                continue
            if snr_values is not None:
                # Accept if the folder name contains any of the requested SNR
                tag = snr_dir.name            # e.g. "snr_-10dB"
                nums = [int(s) for s in tag.replace("snr_", "").replace("dB", "")
                        .replace("+", "").split() if s.lstrip("-").isdigit()
                        or s.replace("-", "").isdigit()]
                if not any(n in snr_values for n in nums):
                    continue
            for p in sorted(snr_dir.glob("*.wav")):
                self.samples.append((p, 1, snr_dir.name))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, int, str]:
        path, label, snr_tag = self.samples[idx]
        spec = self.extractor(str(path))
        return spec, label, snr_tag


# ═══════════════════════════════════════════════════════════════════════════
#  DataLoader factories
# ═══════════════════════════════════════════════════════════════════════════

def get_train_loader(
    train_dir:   str | Path,
    cfg:         Optional[AudioConfig] = None,
    batch_size:  int  = 32,
    num_workers: int  = 4,
    shuffle:     bool = True,
    pin_memory:  Optional[bool] = None,
) -> DataLoader:
    """DataLoader for the training split (normal samples only)."""
    cfg  = cfg or AudioConfig()
    ext  = LogMelExtractor(cfg=cfg)
    ds   = AudioDataset(train_dir, extractor=ext, label=0)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=pin_memory if pin_memory is not None else _auto_pin_memory(),
        drop_last=True,
    )


def get_val_loader(
    val_dir:     str | Path,
    cfg:         Optional[AudioConfig] = None,
    batch_size:  int = 64,
    num_workers: int = 4,
    pin_memory:  Optional[bool] = None,
) -> DataLoader:
    """DataLoader for the validation split (normal samples only)."""
    cfg  = cfg or AudioConfig()
    ext  = LogMelExtractor(cfg=cfg)
    ds   = AudioDataset(val_dir, extractor=ext, label=0)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory if pin_memory is not None else _auto_pin_memory(),
    )


def get_test_loader(
    normal_dir:  str | Path,
    anomaly_dir: str | Path,
    cfg:         Optional[AudioConfig] = None,
    batch_size:  int = 64,
    num_workers: int = 4,
    pin_memory:  Optional[bool] = None,
) -> DataLoader:
    """DataLoader for the test split (normal + anomaly, with labels)."""
    cfg = cfg or AudioConfig()
    ext = LogMelExtractor(cfg=cfg)
    ds  = AnomalyTestDataset(normal_dir, anomaly_dir, extractor=ext)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory if pin_memory is not None else _auto_pin_memory(),
    )


def make_kfold_loaders(
    all_files:   list[Path],
    fold_idx:    list[int],
    val_indices: list[int],
    cfg:         Optional[AudioConfig] = None,
    batch_size:  int = 32,
    num_workers: int = 4,
) -> tuple[DataLoader, DataLoader]:
    """
    Build train / val DataLoaders for one K-fold split.

    Args:
        all_files:   Complete list of file paths in the training set.
        fold_idx:    Indices (into all_files) used for training.
        val_indices: Indices (into all_files) used for validation.
        cfg:         AudioConfig.
        batch_size:  Mini-batch size.
        num_workers: Worker processes.

    Returns:
        (train_loader, val_loader)
    """
    cfg = cfg or AudioConfig()
    ext = LogMelExtractor(cfg=cfg)

    class _FileListDataset(Dataset):
        def __init__(self, paths: list[Path]) -> None:
            self.paths = paths
        def __len__(self) -> int:
            return len(self.paths)
        def __getitem__(self, i: int) -> tuple[torch.Tensor, int]:
            return ext(str(self.paths[i])), 0   # label=0 (all normal)

    train_ds = _FileListDataset([all_files[i] for i in fold_idx])
    val_ds   = _FileListDataset([all_files[i] for i in val_indices])

    _pin = _auto_pin_memory()
    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=_pin, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=num_workers, pin_memory=_pin,
    )
    return train_loader, val_loader
